backend:
  name: git-gateway
  branch: main
  repo: HusainMkd/AstroAccountantsLondon # change this to your repo
  site_domain: www-auroraaccountantslondon.netlify.app # change this to your domain
  base_url: https://www-auroraaccountantslondon.netlify.app/ # change this to your prod URL
  auth_endpoint: oauth # the oauth route provided by the integration

media_folder: 'src/assets/images'
public_folder: '/assets/images'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
      - { label: 'Metadata', name: 'metadata', widget: 'object', fields: [
          { label: 'Canonical', name: 'canonical', widget: 'string' },
        ] }
